/**
 * SPRINT 0: Decision Engine Type Definitions
 * Updated with new operators: below-baseline, above-baseline, outside-range
 * Updated with cooldown_hours
 */

// ============================================
// ENUMS & CONSTANTS
// ============================================

export type DecisionType = 
  | 'rest'
  | 'modify_load'
  | 'review_athlete'
  | 'medical_referral'
  | 'celebrate'
  | 'custom';

export type DecisionPriority = 
  | 'critical'
  | 'high'
  | 'medium'
  | 'low';

export type DecisionStatus = 
  | 'pending'
  | 'accepted'
  | 'rejected'
  | 'expired';

export type RuleConnector = 
  | 'AND'
  | 'OR'
  | null;

/**
 * NEW: Updated operators with baseline-aware options
 */
export type RuleOperator = 
  // Absolute comparisons
  | 'less-than' 
  | 'greater-than' 
  | 'equals'
  // NEW: Baseline-relative comparisons
  | 'below-baseline'      // X% below athlete's baseline
  | 'above-baseline'      // X% above athlete's baseline
  | 'outside-range';      // Outside ±X% of baseline

export const OPERATOR_LABELS: Record<RuleOperator, string> = {
  'less-than': 'Less than',
  'greater-than': 'Greater than',
  'equals': 'Equals',
  'below-baseline': 'Below baseline by',
  'above-baseline': 'Above baseline by',
  'outside-range': 'Outside baseline range',
};

export const OPERATOR_DESCRIPTIONS: Record<RuleOperator, string> = {
  'less-than': 'Value is below absolute threshold',
  'greater-than': 'Value is above absolute threshold',
  'equals': 'Value equals exact value',
  'below-baseline': 'Value is X% below athlete\'s personal baseline',
  'above-baseline': 'Value is X% above athlete\'s personal baseline',
  'outside-range': 'Value is outside ±X% of athlete\'s baseline',
};

// ============================================
// RULE DEFINITION
// ============================================

export interface BeliefRule {
  id: string;
  workspaceId: string;
  
  // Basic info
  name: string;
  description?: string;
  
  // Conditions
  conditions: RuleCondition[];
  
  // Decision output
  decisionType: DecisionType;
  decisionTemplate: string;  // Template with {{metric_name}} placeholders
  priority: number;           // 0-200 (higher = more important)
  
  // NEW: Cooldown to prevent spam
  cooldownHours: number;      // Min hours between triggers (default: 24)
  
  // Metadata
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
  
  // Stats
  triggerCount: number;
  lastTriggered?: string;
}

export interface RuleCondition {
  metricId: string;
  operator: RuleOperator;
  value: number;              // Percentage if baseline operator, absolute if not
  absoluteValue?: number;     // NEW: Fallback if no baseline available
  connector: RuleConnector;
}

// ============================================
// DECISION
// ============================================

export interface Decision {
  id: string;
  workspaceId: string;
  athleteId: string;
  
  // Content
  type: DecisionType;
  title: string;
  description: string;
  priority: DecisionPriority;
  
  // Context
  ruleId?: string;            // If generated by rule
  triggeringMetrics?: TriggeringMetric[];
  
  // Status
  status: DecisionStatus;
  expiresAt?: string;
  
  // Actions taken
  actionedBy?: string;
  actionedAt?: string;
  actionNotes?: string;
  
  // Metadata
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface TriggeringMetric {
  metricId: string;
  metricName: string;
  currentValue: number;
  threshold: number;
  baseline?: number;
  operator: RuleOperator;
  percentFromBaseline?: number;
}

// ============================================
// DECISION CONTEXT
// ============================================

/**
 * Full context for decision with all related data
 */
export interface DecisionContext {
  decision: Decision;
  athlete?: {
    id: string;
    name: string;
    avatar?: string;
  };
  rule?: BeliefRule;
  metrics?: {
    metricId: string;
    name: string;
    currentValue: number;
    baseline?: number;
    zone?: string;
  }[];
}

// ============================================
// THRESHOLD CALCULATION RESULT
// ============================================

/**
 * NEW: Enhanced result from threshold calculator
 * Supports both single thresholds and ranges
 */
export interface ThresholdResult {
  // Single threshold (for most operators)
  threshold?: number;
  
  // Range thresholds (for outside-range operator)
  thresholdMin?: number;
  thresholdMax?: number;
  
  // Context
  baseline: number;
  currentValue: number;
  percentFromBaseline: number;
  
  // Result
  exceeded: boolean;
  
  // Debug info
  operator: RuleOperator;
  rawConditionValue: number;
}

// ============================================
// API REQUEST/RESPONSE TYPES
// ============================================

export interface CreateRuleRequest {
  workspaceId: string;
  name: string;
  description?: string;
  conditions: Omit<RuleCondition, 'connector'>[];
  decisionType: DecisionType;
  decisionTemplate: string;
  priority?: number;
  cooldownHours?: number;
}

export interface UpdateRuleRequest extends Partial<CreateRuleRequest> {
  id: string;
}

export interface CreateDecisionRequest {
  workspaceId: string;
  athleteId: string;
  type: DecisionType;
  title: string;
  description: string;
  priority: DecisionPriority;
  ruleId?: string;
  triggeringMetrics?: TriggeringMetric[];
  expiresAt?: string;
}

export interface ActionDecisionRequest {
  decisionId: string;
  status: 'accepted' | 'rejected';
  notes?: string;
}

export interface GetDecisionsRequest {
  workspaceId?: string;
  athleteId?: string;
  status?: DecisionStatus;
  type?: DecisionType;
  priority?: DecisionPriority;
  startDate?: string;
  endDate?: string;
  limit?: number;
}

// ============================================
// RULE EVALUATION
// ============================================

export interface RuleEvaluationContext {
  rule: BeliefRule;
  athleteId: string;
  metricValues: Record<string, number>;  // metricId -> current value
  baselines: Record<string, number>;     // metricId -> baseline
}

export interface RuleEvaluationResult {
  triggered: boolean;
  conditions: ConditionEvaluationResult[];
  decision?: Decision;
  reason?: string;
}

export interface ConditionEvaluationResult {
  condition: RuleCondition;
  thresholdResult: ThresholdResult;
  met: boolean;
}

// ============================================
// HARDCODED RULES (System Rules)
// ============================================

export interface HardcodedRule extends Omit<BeliefRule, 'id' | 'workspaceId' | 'createdBy' | 'createdAt' | 'updatedAt'> {
  id: string;
  isSystem: true;
  canEdit: false;
  canDelete: false;
}

/**
 * Priority ranges for rules:
 * 200+: System critical (injuries, medical)
 * 150-199: Critical (severe fatigue, overtraining)
 * 100-149: High (moderate concerns)
 * 50-99: Medium (attention needed)
 * 0-49: Low (monitoring)
 */
export const RULE_PRIORITY_RANGES = {
  SYSTEM_CRITICAL: { min: 200, max: 250 },
  CRITICAL: { min: 150, max: 199 },
  HIGH: { min: 100, max: 149 },
  MEDIUM: { min: 50, max: 99 },
  LOW: { min: 0, max: 49 },
} as const;

// ============================================
// VALIDATION
// ============================================

export interface RuleValidationResult {
  valid: boolean;
  errors: string[];
  warnings?: string[];
}

export function validateRule(rule: Partial<BeliefRule>): RuleValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  // Basic validation
  if (!rule.name) errors.push('Name is required');
  if (!rule.decisionType) errors.push('Decision type is required');
  if (!rule.decisionTemplate) errors.push('Decision template is required');
  
  // Conditions validation
  if (!rule.conditions || rule.conditions.length === 0) {
    errors.push('At least one condition is required');
  } else {
    rule.conditions.forEach((condition, index) => {
      if (!condition.metricId) {
        errors.push(`Condition ${index + 1}: Metric is required`);
      }
      if (!condition.operator) {
        errors.push(`Condition ${index + 1}: Operator is required`);
      }
      if (condition.value === undefined || condition.value === null) {
        errors.push(`Condition ${index + 1}: Value is required`);
      }
      
      // Baseline operator validation
      const isBaselineOperator = ['below-baseline', 'above-baseline', 'outside-range'].includes(condition.operator);
      if (isBaselineOperator && !condition.absoluteValue) {
        warnings.push(`Condition ${index + 1}: No fallback value set - will skip if baseline unavailable`);
      }
    });
  }
  
  // Priority validation
  if (rule.priority !== undefined) {
    if (rule.priority < 0 || rule.priority > 250) {
      errors.push('Priority must be between 0 and 250');
    }
  }
  
  // Cooldown validation
  if (rule.cooldownHours !== undefined) {
    if (rule.cooldownHours < 0) {
      errors.push('Cooldown hours cannot be negative');
    }
    if (rule.cooldownHours > 168) {
      warnings.push('Cooldown > 1 week may cause rule to rarely trigger');
    }
  }
  
  return {
    valid: errors.length === 0,
    errors,
    warnings: warnings.length > 0 ? warnings : undefined,
  };
}

// ============================================
// UTILITY FUNCTIONS
// ============================================

/**
 * Check if rule is in cooldown
 */
export function isInCooldown(rule: BeliefRule): boolean {
  if (!rule.lastTriggered) return false;
  
  const cooldownEnd = new Date(rule.lastTriggered);
  cooldownEnd.setHours(cooldownEnd.getHours() + (rule.cooldownHours || 24));
  
  return new Date() < cooldownEnd;
}

/**
 * Get cooldown end time
 */
export function getCooldownEnd(rule: BeliefRule): Date | null {
  if (!rule.lastTriggered) return null;
  
  const cooldownEnd = new Date(rule.lastTriggered);
  cooldownEnd.setHours(cooldownEnd.getHours() + (rule.cooldownHours || 24));
  
  return cooldownEnd;
}

/**
 * Format rule condition as human-readable string
 */
export function formatCondition(condition: RuleCondition, metricName?: string): string {
  const metric = metricName || 'Metric';
  const operator = OPERATOR_LABELS[condition.operator];
  
  switch (condition.operator) {
    case 'below-baseline':
    case 'above-baseline':
      return `${metric} ${operator.toLowerCase()} ${condition.value}%`;
    
    case 'outside-range':
      return `${metric} ${operator.toLowerCase()} ±${condition.value}%`;
    
    default:
      return `${metric} ${operator.toLowerCase()} ${condition.value}`;
  }
}

/**
 * Get priority label
 */
export function getPriorityLabel(priority: number): DecisionPriority {
  if (priority >= RULE_PRIORITY_RANGES.CRITICAL.min) return 'critical';
  if (priority >= RULE_PRIORITY_RANGES.HIGH.min) return 'high';
  if (priority >= RULE_PRIORITY_RANGES.MEDIUM.min) return 'medium';
  return 'low';
}

/**
 * Convert rule to decision template
 */
export function renderDecisionTemplate(
  template: string,
  metrics: Record<string, { name: string; value: number; baseline?: number }>
): string {
  let rendered = template;
  
  Object.entries(metrics).forEach(([metricId, data]) => {
    rendered = rendered
      .replace(new RegExp(`{{${metricId}}}`, 'g'), String(data.value))
      .replace(new RegExp(`{{${metricId}_name}}`, 'g'), data.name)
      .replace(new RegExp(`{{${metricId}_baseline}}`, 'g'), String(data.baseline || 'N/A'));
  });
  
  return rendered;
}

// ============================================
// EXPORTS
// ============================================

export type {
  BeliefRule,
  RuleCondition,
  Decision,
  TriggeringMetric,
  DecisionContext,
  ThresholdResult,
  CreateRuleRequest,
  UpdateRuleRequest,
  CreateDecisionRequest,
  ActionDecisionRequest,
  GetDecisionsRequest,
  RuleEvaluationContext,
  RuleEvaluationResult,
  ConditionEvaluationResult,
  HardcodedRule,
  RuleValidationResult,
};

export {
  OPERATOR_LABELS,
  OPERATOR_DESCRIPTIONS,
  RULE_PRIORITY_RANGES,
  validateRule,
  isInCooldown,
  getCooldownEnd,
  formatCondition,
  getPriorityLabel,
  renderDecisionTemplate,
};
