/**
 * Decision Engine - TypeScript Interfaces
 * 
 * FASE 8: Decision Engine V1 (Hard-coded Rules)
 * 
 * Core types for the automated decision-making system that analyzes
 * athlete metrics and generates recommendations for coaches.
 * 
 * Flow:
 * 1. Gather athlete metrics (current + historical)
 * 2. Evaluate rules against metrics
 * 3. Generate decisions when conditions met
 * 4. Store decisions with priority & confidence
 * 5. Coach sees decisions in UI (Fase 9)
 * 6. Coach applies or dismisses decisions
 */

// ============================================================================
// DECISION TYPES
// ============================================================================

/**
 * Type of decision/recommendation
 */
export type DecisionType = 
  | 'reduce-load'        // Reduce training load
  | 'rest-day'           // Schedule rest day
  | 'alert'              // Monitor athlete closely
  | 'increase-load'      // Can increase load (future)
  | 'adjust-program'     // Modify training program
  | 'medical-evaluation' // Requires medical attention
  | 'nutrition-focus'    // Focus on nutrition/recovery (future)
  | 'mental-health';     // Mental health check (future)

/**
 * Priority level of decision
 */
export type DecisionPriority = 
  | 'critical'  // Immediate action required (red)
  | 'high'      // Action needed soon (orange)
  | 'medium'    // Monitor situation (yellow)
  | 'low';      // FYI only (blue)

/**
 * Current status of decision
 */
export type DecisionStatus = 
  | 'pending'    // Awaiting coach action
  | 'applied'    // Coach applied the recommendation
  | 'dismissed'  // Coach dismissed the recommendation
  | 'expired';   // Decision expired (time-based)

/**
 * Metric status color coding
 */
export type MetricStatus = 
  | 'green'   // Within healthy range
  | 'yellow'  // Warning zone
  | 'red';    // Critical zone

// ============================================================================
// CORE INTERFACES
// ============================================================================

/**
 * Metric used in decision-making
 * 
 * Provides context about which metrics influenced the decision
 * and their relative importance (weight).
 */
export interface MetricUsed {
  metricId: string;
  name: string;
  value: number | string;
  weight: number;              // 0-1 (importance in decision)
  status: MetricStatus;        // Visual indicator
  threshold?: number;          // Threshold that was crossed (optional)
  baseline?: number;           // Baseline value for comparison (optional)
}

/**
 * Decision generated by the engine
 * 
 * Represents an automated recommendation for a specific athlete
 * based on their current metrics and historical data.
 */
export interface Decision {
  id: string;
  workspaceId: string;
  athleteId: string;
  athleteName?: string;        // Denormalized for UI
  
  // Classification
  type: DecisionType;
  priority: DecisionPriority;
  status: DecisionStatus;
  
  // Content
  recommendation: string;      // Short actionable recommendation
  reasoning: string;           // Detailed explanation WHY
  
  // Context
  metricsUsed: MetricUsed[];   // Metrics that triggered this decision
  ruleId?: string;             // Which rule generated this (if from rule)
  confidence: number;          // 0-1 confidence score
  
  // Metadata
  createdAt: string;           // ISO timestamp
  expiresAt?: string;          // Auto-expire old decisions
  appliedAt?: string;          // When coach applied
  appliedBy?: string;          // Coach user ID
  dismissedAt?: string;        // When coach dismissed
  dismissedBy?: string;        // Coach user ID
  dismissReason?: string;      // Why dismissed (optional)
  notes?: string;              // Coach can add notes
  
  // Analytics (future)
  viewedAt?: string;           // When first viewed
  viewCount?: number;          // How many times viewed
}

/**
 * Rule definition for decision-making
 * 
 * Each rule evaluates metrics and generates decisions when
 * specific conditions are met.
 */
export interface DecisionRule {
  id: string;
  name: string;
  description: string;
  priority: DecisionPriority;
  
  // Evaluation logic
  conditions: (context: MetricContext) => boolean;
  generate: (context: MetricContext) => Omit<Decision, 'id' | 'workspaceId' | 'status' | 'createdAt'>;
  
  // Configuration
  enabled: boolean;
  cooldown?: number;           // Hours before same rule can trigger again for same athlete
  
  // Metadata
  category?: 'recovery' | 'load' | 'injury' | 'performance';
  version?: string;            // For tracking rule changes
  createdAt?: string;
  updatedAt?: string;
}

/**
 * Metric context for rule evaluation
 * 
 * Contains all metric data needed to evaluate rules for a single athlete.
 */
export interface MetricContext {
  athleteId: string;
  workspaceId: string;
  
  // Current metrics (most recent values)
  currentMetrics: Record<string, number>;
  
  // Historical data
  historicalMetrics: {
    last7d: Record<string, number[]>;   // Last 7 days per metric
    last30d: Record<string, number[]>;  // Last 30 days per metric
    baseline: Record<string, number>;   // 4-week baseline per metric
  };
  
  // Athlete profile (for context)
  athleteProfile?: {
    name: string;
    sport?: string;
    age?: number;
    gender?: string;
    position?: string;
  };
  
  // Timestamp when context was built
  contextBuiltAt?: string;
}

/**
 * Result of evaluating a single rule
 */
export interface RuleEvaluationResult {
  ruleId: string;
  ruleName: string;
  triggered: boolean;
  decision?: Decision;         // Only if triggered
  evaluatedAt: string;
  executionTime: number;       // Milliseconds
  error?: string;              // If evaluation failed
}

/**
 * Result of running entire engine for workspace
 */
export interface EngineRunResult {
  workspaceId: string;
  athletesEvaluated: number;
  rulesEvaluated: number;
  decisionsCreated: number;
  decisionsSkipped: number;    // Cooldown or duplicate
  errors: string[];
  warnings: string[];
  duration: number;            // Total milliseconds
  timestamp: string;
  
  // Detailed breakdown
  breakdown?: {
    byPriority: Record<DecisionPriority, number>;
    byType: Record<DecisionType, number>;
    byRule: Record<string, number>;
  };
}

// ============================================================================
// AGGREGATION TYPES
// ============================================================================

/**
 * Metric value with timestamp
 */
export interface MetricValue {
  value: number;
  timestamp: string;
  source?: string;             // 'manual', 'form', 'integration'
}

/**
 * Aggregated metric statistics
 */
export interface MetricStats {
  metricId: string;
  athleteId: string;
  
  // Basic stats
  current: number;             // Most recent value
  min: number;
  max: number;
  avg: number;
  median: number;
  stdDev: number;
  
  // Trend analysis
  trend: 'increasing' | 'decreasing' | 'stable';
  changePercent: number;       // % change vs baseline
  
  // Time windows
  last7dAvg: number;
  last30dAvg: number;
  baseline: number;            // 4-week average
  
  // Computed at
  computedAt: string;
}

/**
 * ACWR (Acute:Chronic Workload Ratio) calculation
 */
export interface ACWRData {
  athleteId: string;
  acute: number;               // 7-day average
  chronic: number;             // 28-day average
  ratio: number;               // acute / chronic
  status: MetricStatus;        // green (0.8-1.3), yellow (1.3-1.5), red (>1.5 or <0.8)
  recommendation: string;
  computedAt: string;
}

// ============================================================================
// API REQUEST/RESPONSE TYPES
// ============================================================================

/**
 * Request to list decisions
 */
export interface ListDecisionsRequest {
  workspaceId: string;
  athleteId?: string;          // Filter by athlete
  status?: DecisionStatus;     // Filter by status
  priority?: DecisionPriority; // Filter by priority
  type?: DecisionType;         // Filter by type
  limit?: number;              // Max results (default 50)
  offset?: number;             // Pagination
  sortBy?: 'createdAt' | 'priority' | 'confidence';
  sortOrder?: 'asc' | 'desc';
}

/**
 * Response with decisions list
 */
export interface ListDecisionsResponse {
  decisions: Decision[];
  total: number;
  hasMore: boolean;
  filters: {
    status?: DecisionStatus;
    priority?: DecisionPriority;
    athleteId?: string;
  };
}

/**
 * Request to update decision status
 */
export interface UpdateDecisionRequest {
  status: 'applied' | 'dismissed';
  notes?: string;
  dismissReason?: string;      // Required if dismissing
}

/**
 * Request to manually trigger engine
 */
export interface TriggerEngineRequest {
  workspaceId: string;
  athleteIds?: string[];       // Specific athletes (or all)
  ruleIds?: string[];          // Specific rules (or all)
  force?: boolean;             // Ignore cooldowns
}

// ============================================================================
// HELPER TYPES
// ============================================================================

/**
 * Decision priority configuration
 */
export interface PriorityConfig {
  priority: DecisionPriority;
  color: string;               // Tailwind color (e.g., 'red', 'amber')
  label: string;
  icon: string;                // Icon name
  expiryHours: number;         // Auto-expire after X hours
}

/**
 * Decision type configuration
 */
export interface DecisionTypeConfig {
  type: DecisionType;
  label: string;
  description: string;
  icon: string;
  defaultPriority: DecisionPriority;
}

/**
 * Cooldown tracking
 */
export interface RuleCooldown {
  ruleId: string;
  athleteId: string;
  lastTriggered: string;
  expiresAt: string;
}

// ============================================================================
// CONSTANTS
// ============================================================================

/**
 * Priority configurations
 */
export const PRIORITY_CONFIGS: Record<DecisionPriority, PriorityConfig> = {
  critical: {
    priority: 'critical',
    color: 'red',
    label: 'Crítico',
    icon: 'AlertTriangle',
    expiryHours: 24,
  },
  high: {
    priority: 'high',
    color: 'amber',
    label: 'Alto',
    icon: 'AlertCircle',
    expiryHours: 48,
  },
  medium: {
    priority: 'medium',
    color: 'yellow',
    label: 'Médio',
    icon: 'Info',
    expiryHours: 72,
  },
  low: {
    priority: 'low',
    color: 'blue',
    label: 'Baixo',
    icon: 'MessageCircle',
    expiryHours: 168, // 1 week
  },
};

/**
 * Decision type configurations
 */
export const DECISION_TYPE_CONFIGS: Record<DecisionType, DecisionTypeConfig> = {
  'reduce-load': {
    type: 'reduce-load',
    label: 'Reduzir Carga',
    description: 'Reduzir volume ou intensidade do treino',
    icon: 'TrendingDown',
    defaultPriority: 'high',
  },
  'rest-day': {
    type: 'rest-day',
    label: 'Dia de Descanso',
    description: 'Agendar descanso ou treino regenerativo',
    icon: 'Moon',
    defaultPriority: 'high',
  },
  'alert': {
    type: 'alert',
    label: 'Alerta',
    description: 'Monitorizar atleta de perto',
    icon: 'Bell',
    defaultPriority: 'medium',
  },
  'increase-load': {
    type: 'increase-load',
    label: 'Aumentar Carga',
    description: 'Atleta pode progredir',
    icon: 'TrendingUp',
    defaultPriority: 'low',
  },
  'adjust-program': {
    type: 'adjust-program',
    label: 'Ajustar Programa',
    description: 'Modificar planeamento',
    icon: 'Settings',
    defaultPriority: 'medium',
  },
  'medical-evaluation': {
    type: 'medical-evaluation',
    label: 'Avaliação Médica',
    description: 'Requer atenção médica',
    icon: 'Heart',
    defaultPriority: 'critical',
  },
  'nutrition-focus': {
    type: 'nutrition-focus',
    label: 'Foco Nutricional',
    description: 'Melhorar nutrição/recuperação',
    icon: 'Apple',
    defaultPriority: 'low',
  },
  'mental-health': {
    type: 'mental-health',
    label: 'Saúde Mental',
    description: 'Check-in psicológico',
    icon: 'Brain',
    defaultPriority: 'medium',
  },
};

/**
 * Safe ACWR zone
 */
export const ACWR_SAFE_ZONE = {
  min: 0.8,
  optimal: 1.0,
  max: 1.3,
  danger: 1.5,
} as const;

/**
 * Default cooldown periods (hours)
 */
export const DEFAULT_COOLDOWNS = {
  critical: 12,  // Can trigger twice per day
  high: 24,      // Once per day
  medium: 48,    // Every 2 days
  low: 72,       // Every 3 days
} as const;

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Check if decision is pending
 */
export function isPending(decision: Decision): boolean {
  return decision.status === 'pending' && !isExpired(decision);
}

/**
 * Check if decision is expired
 */
export function isExpired(decision: Decision): boolean {
  if (!decision.expiresAt) return false;
  return new Date(decision.expiresAt) < new Date();
}

/**
 * Check if decision is actionable (pending and not expired)
 */
export function isActionable(decision: Decision): boolean {
  return isPending(decision) && !isExpired(decision);
}

/**
 * Check if decision is critical priority
 */
export function isCritical(decision: Decision): boolean {
  return decision.priority === 'critical';
}

/**
 * Get priority color
 */
export function getPriorityColor(priority: DecisionPriority): string {
  return PRIORITY_CONFIGS[priority].color;
}

/**
 * Get priority label
 */
export function getPriorityLabel(priority: DecisionPriority): string {
  return PRIORITY_CONFIGS[priority].label;
}

/**
 * Get decision type label
 */
export function getDecisionTypeLabel(type: DecisionType): string {
  return DECISION_TYPE_CONFIGS[type].label;
}

// ============================================================================
// EXPORTS
// ============================================================================

export type {
  Decision,
  DecisionRule,
  MetricContext,
  RuleEvaluationResult,
  EngineRunResult,
  MetricValue,
  MetricStats,
  ACWRData,
  ListDecisionsRequest,
  ListDecisionsResponse,
  UpdateDecisionRequest,
  TriggerEngineRequest,
  RuleCooldown,
};
